<!DOCTYPE html>
<html>
<head>
    <title>JS Errors</title>
</head>
<body>
    <h1> <u> JavaScript Error Handling</u></h1>
    <!--<p>Please input a number between 5 and 10:</p> -->
    <h3> Even and Odd numbers</h3>
    <input id="demo" type="text">
<button type="button" onclick="myFunction()">Test Input</button>
<p id="err_ex"></p>
<script>
function myFunction() {
  const message = document.getElementById("err_ex");
  message.innerHTML = "";
  let x = document.getElementById("demo").value;
  try {
    if(x.trim() == "") throw "empty";
    if(isNaN(x)) throw "not a number";
    x = Number(x);
    if(x %2==0) throw "Even number";
    if(x %2!==0 ) throw "Odd number";
  }
  catch(err) {
    message.innerHTML = "Given Input is " + err;
  }
}
</script> <hr>

<h3>Finally exception</h3>
<p>The finally statement lets you execute code, after try and catch, regardless of the result:</p>
<input id="input" type="text">
<button type="button" onclick="myFunction1()">Test Input</button>
<p id="p01"></p>
<script>
function myFunction1() {
  const message = document.getElementById("p01");
  message.innerHTML = "";
  let x = document.getElementById("demo").value;
  try { 
    if(x.trim() == "")  throw "is empty";
    if(isNaN(x)) throw "is not a number";
    x = Number(x);
    if(x > 10)   throw "is too high";
    if(x < 5)  throw "is too low";
  }
  catch(err) {
    message.innerHTML = "Input " + err;
  }
  finally {
    document.getElementById("input").value = x;
  }
}
</script> <hr>

<h1>Error Objects</h1>
<h2>Range Error</h2>
<p>You cannot set the number of significant digits too high:</p>
<p id="range">
<script>
let num = 1;
try {
  num.toPrecision(500);
}
catch(err) {
  document.getElementById("range").innerHTML = err.name;
}
</script> <hr>

<h2>The ReferenceError</h2>
<p>You cannot use the value of a non-existing variable:</p>
<p id="reference"></p>
<script>
let x = 5;
try {
  x = y + 1;
}
catch(err) {
  document.getElementById("reference").innerHTML = err.name;
}
</script> <hr>

<h2>The SyntaxError</h2>
<p>You cannot evaluate code that contains a syntax error:</p>
<p id="syntax"></p>
<script>
try {
  eval("alert('Hello)");
}
catch(err) {
  document.getElementById("syntax").innerHTML = err.name;
}
</script> <hr>

<h2>The TypeError</h2>
<p>You cannot convert a number to upper case:</p>
<p id="type"></p>
<script>
let Num = 1;
try {
  Num.toUpperCase();
}
catch(err) {
  document.getElementById("type").innerHTML = err.name;
}
</script> <hr>

<h2>The URIError</h2>
<p>Some characters cannot be decoded with decodeURI():</p>
<p id="URI"></p>
<script>
try {
  decodeURI("%%%");
}
catch(err) {
  document.getElementById("URI").innerHTML = err.name;
}
</script> <hr>
</body>
</html>